project:
  type: book
  output-dir: ../docs
  execute-dir: project

book:
  title: "RW-FFM Fuel Analysis"
  author: "Judson Fisher"
  date: "4/1/2023"
  chapters:
    - index.qmd
    - part: ./ground/ground.qmd
      chapters:
        - ./ground/named_and_numbered.qmd
        - ./ground/visualize_3d.qmd
    - references.qmd

bibliography: references.bib
resources: rw.db

format:
  html:
    theme: cosmo

