project:
  type: book
  output-dir: ../docs
  execute-dir: project
  # # I don't wan't to do this every time I render the site
  pre-render: scripts/sqlite_to_csv.py 
  post-render: 
    - cp ../data/rw.db ../docs
    - cp ../data/rwffm_csvs.zip ../docs

book:
  title: "RW-FFM Fuel Analysis"
  author: "Judson Fisher"
  date: "4/1/2023"
  chapters:
    - index.qmd
    - data_description.qmd
    - part: ./ground/ground.qmd
      chapters:
        - ./ground/named_and_numbered.qmd
        - ./ground/visualize_3d.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

